#!/usr/bin/env bash
# Collect labels on the student's own Gate-4-through-6 state distribution.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CHECKPOINT="${CHECKPOINT:?set CHECKPOINT to an FP32 32-observation policy}"
OUTPUT="${OUTPUT:?set OUTPUT to the DAgger dataset path}"
EPISODES="${EPISODES:-256}"
STUDENT_PROBABILITY="${STUDENT_PROBABILITY:-0.5}"
SEED="${SEED:-22000}"

if [[ ! -x build/collect_full_policy_teacher ]]; then
    clang -O2 -DNDEBUG -I. scripts/collect_full_policy_teacher.c \
        -o build/collect_full_policy_teacher -lm
fi
mkdir -p "$(dirname "$OUTPUT")"

env \
    CHECKPOINT_LAYOUT_PRECISION_BYTES=4 \
    SEED="$SEED" EPISODE_SEED_SEQUENCE=1 \
    POLICY_HZ=60 NUM_GATES=6 \
    START_GATE_INDEX=3 START_ELAPSED_TIME=10.85 \
    START_ELAPSED_TIME_JITTER=0.55 \
    START_X=64.3 START_Y=-0.5 START_Z=-6.9 \
    START_X_JITTER=6 START_Y_JITTER=5 START_Z_JITTER=2 \
    START_VX=8.5 START_VY=0.4 START_VZ=-5 \
    START_VX_JITTER=4 START_VY_JITTER=2 START_VZ_JITTER=2.5 \
    START_QW=0.99529518 START_QX=-0.03851571 \
    START_QY=0.08873983 START_QZ=0.00541173 \
    START_ROLL_JITTER_RAD=0.22 START_PITCH_JITTER_RAD=0.04 \
    START_YAW_JITTER_RAD=0.04 \
    START_WX=-0.40 START_WY=0.33 START_WZ=-0.05 \
    START_WX_JITTER=0.25 START_WY_JITTER=0.30 START_WZ_JITTER=0.10 \
    GATE4_X=122 GATE4_Y=5.10711 GATE4_Z=-18.24322 \
    GATE5_X=148 GATE5_Y=5.10711 GATE5_Z=-18.24322 \
    GATE_RADIUS=0.95 GATE0_RADIUS=0.75 GATE1_RADIUS=0 GATE2_RADIUS=0 \
    GATE3_RADIUS=0.875 GATE4_RADIUS=0 GATE5_RADIUS=0.75 \
    OBSERVABLE_GATE_PROGRESS=1 OBSERVABLE_GATE_INDEX_DENOMINATOR=6 \
    OBSERVABLE_GATE_PHASE_ONEHOT=0 \
    SITL_GATE_TRANSITION_MIN_FORWARD_SPEED=4.1875 \
    SITL_GATE_OBS_SAMPLE_INTERVAL_STEPS=4 \
    SITL_GATE_MOTION_PREDICT_DROPOUT=1 \
    SITL_GATE_MOTION_CONTROL_ACCEL_GAIN=4.295 \
    POLICY_TEACHER=1 \
    TEACHER_SPLINE_LABEL_FROM_GATE=3 TEACHER_SPLINE_LABEL_UNTIL_GATE=6 \
    TEACHER_SPLINE_FULL_COURSE_ORIGIN=1 \
    TEACHER_SPLINE_LATERAL_POSITION_KP="${TEACHER_SPLINE_LATERAL_POSITION_KP:-1.5}" \
    TEACHER_SPLINE_CLOSE_LATERAL_POSITION_KP="${TEACHER_SPLINE_CLOSE_LATERAL_POSITION_KP:-5.0}" \
    TEACHER_SPLINE_LATERAL_VELOCITY_KD="${TEACHER_SPLINE_LATERAL_VELOCITY_KD:-2.7}" \
    TEACHER_SPLINE_VERTICAL_POSITION_KP="${TEACHER_SPLINE_VERTICAL_POSITION_KP:-2.2}" \
    TEACHER_SPLINE_VERTICAL_VELOCITY_KD="${TEACHER_SPLINE_VERTICAL_VELOCITY_KD:-2.0}" \
    TEACHER_SPLINE_CLOSE_POSITION_RANGE_M=10 \
    TEACHER_SPLINE_CURVATURE_SCALE=1 \
    TEACHER_SPLINE_DERIVATIVE_LOOKAHEAD_M=6.10 \
    TEACHER_SPLINE_VERTICAL_DERIVATIVE_LOOKAHEAD_M=0 \
    TEACHER_SPLINE_DERIVATIVE_LOOKAHEAD_FROM_GATE=2 \
    TEACHER_SPLINE_EXIT_TANGENTS=1 \
    TEACHER_SPLINE_EXIT_TANGENT_FROM_GATE=2 \
    TEACHER_SPLINE_EXIT_SLOPE_SCALE=1 \
    build/collect_full_policy_teacher \
        "$OUTPUT" "$EPISODES" "$CHECKPOINT" "$STUDENT_PROBABILITY" 0 0
